#!/bin/sh -e

# Initialize the URL to a default
snapctl set \
    url="https://www.ubuntu.com/internet-of-things" \
    resettime="60" \
    shownav="false" \
    hidecursor="false" \
    disablekiosk="false"
